/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SafeScoutingRouteImport } from './routes/safe-scouting'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScoutIndexRouteImport } from './routes/scout/index'
import { Route as PlayerIndexRouteImport } from './routes/player/index'
import { Route as ScoutSelectionsRouteImport } from './routes/scout/selections'
import { Route as ScoutProfileRouteImport } from './routes/scout/profile'
import { Route as ScoutExploreRouteImport } from './routes/scout/explore'
import { Route as ResumeUserIdRouteImport } from './routes/resume.$userId'
import { Route as PlayerUploadRouteImport } from './routes/player/upload'
import { Route as PlayerProfileRouteImport } from './routes/player/profile'
import { Route as PlayerExploreRouteImport } from './routes/player/explore'
import { Route as ApiHealthRouteImport } from './routes/api/health'

const SafeScoutingRoute = SafeScoutingRouteImport.update({
  id: '/safe-scouting',
  path: '/safe-scouting',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutIndexRoute = ScoutIndexRouteImport.update({
  id: '/scout/',
  path: '/scout/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/player/',
  path: '/player/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutSelectionsRoute = ScoutSelectionsRouteImport.update({
  id: '/scout/selections',
  path: '/scout/selections',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutProfileRoute = ScoutProfileRouteImport.update({
  id: '/scout/profile',
  path: '/scout/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutExploreRoute = ScoutExploreRouteImport.update({
  id: '/scout/explore',
  path: '/scout/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeUserIdRoute = ResumeUserIdRouteImport.update({
  id: '/resume/$userId',
  path: '/resume/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerUploadRoute = PlayerUploadRouteImport.update({
  id: '/player/upload',
  path: '/player/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerProfileRoute = PlayerProfileRouteImport.update({
  id: '/player/profile',
  path: '/player/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerExploreRoute = PlayerExploreRouteImport.update({
  id: '/player/explore',
  path: '/player/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/mission': typeof MissionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safe-scouting': typeof SafeScoutingRoute
  '/api/health': typeof ApiHealthRoute
  '/player/explore': typeof PlayerExploreRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/upload': typeof PlayerUploadRoute
  '/resume/$userId': typeof ResumeUserIdRoute
  '/scout/explore': typeof ScoutExploreRoute
  '/scout/profile': typeof ScoutProfileRoute
  '/scout/selections': typeof ScoutSelectionsRoute
  '/player/': typeof PlayerIndexRoute
  '/scout/': typeof ScoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/mission': typeof MissionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safe-scouting': typeof SafeScoutingRoute
  '/api/health': typeof ApiHealthRoute
  '/player/explore': typeof PlayerExploreRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/upload': typeof PlayerUploadRoute
  '/resume/$userId': typeof ResumeUserIdRoute
  '/scout/explore': typeof ScoutExploreRoute
  '/scout/profile': typeof ScoutProfileRoute
  '/scout/selections': typeof ScoutSelectionsRoute
  '/player': typeof PlayerIndexRoute
  '/scout': typeof ScoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/mission': typeof MissionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safe-scouting': typeof SafeScoutingRoute
  '/api/health': typeof ApiHealthRoute
  '/player/explore': typeof PlayerExploreRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/upload': typeof PlayerUploadRoute
  '/resume/$userId': typeof ResumeUserIdRoute
  '/scout/explore': typeof ScoutExploreRoute
  '/scout/profile': typeof ScoutProfileRoute
  '/scout/selections': typeof ScoutSelectionsRoute
  '/player/': typeof PlayerIndexRoute
  '/scout/': typeof ScoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/auth'
    | '/faq'
    | '/mission'
    | '/privacy-policy'
    | '/reset-password'
    | '/safe-scouting'
    | '/api/health'
    | '/player/explore'
    | '/player/profile'
    | '/player/upload'
    | '/resume/$userId'
    | '/scout/explore'
    | '/scout/profile'
    | '/scout/selections'
    | '/player/'
    | '/scout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/auth'
    | '/faq'
    | '/mission'
    | '/privacy-policy'
    | '/reset-password'
    | '/safe-scouting'
    | '/api/health'
    | '/player/explore'
    | '/player/profile'
    | '/player/upload'
    | '/resume/$userId'
    | '/scout/explore'
    | '/scout/profile'
    | '/scout/selections'
    | '/player'
    | '/scout'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/auth'
    | '/faq'
    | '/mission'
    | '/privacy-policy'
    | '/reset-password'
    | '/safe-scouting'
    | '/api/health'
    | '/player/explore'
    | '/player/profile'
    | '/player/upload'
    | '/resume/$userId'
    | '/scout/explore'
    | '/scout/profile'
    | '/scout/selections'
    | '/player/'
    | '/scout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  MissionRoute: typeof MissionRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafeScoutingRoute: typeof SafeScoutingRoute
  ApiHealthRoute: typeof ApiHealthRoute
  PlayerExploreRoute: typeof PlayerExploreRoute
  PlayerProfileRoute: typeof PlayerProfileRoute
  PlayerUploadRoute: typeof PlayerUploadRoute
  ResumeUserIdRoute: typeof ResumeUserIdRoute
  ScoutExploreRoute: typeof ScoutExploreRoute
  ScoutProfileRoute: typeof ScoutProfileRoute
  ScoutSelectionsRoute: typeof ScoutSelectionsRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
  ScoutIndexRoute: typeof ScoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safe-scouting': {
      id: '/safe-scouting'
      path: '/safe-scouting'
      fullPath: '/safe-scouting'
      preLoaderRoute: typeof SafeScoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/': {
      id: '/scout/'
      path: '/scout'
      fullPath: '/scout/'
      preLoaderRoute: typeof ScoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/player'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/selections': {
      id: '/scout/selections'
      path: '/scout/selections'
      fullPath: '/scout/selections'
      preLoaderRoute: typeof ScoutSelectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/profile': {
      id: '/scout/profile'
      path: '/scout/profile'
      fullPath: '/scout/profile'
      preLoaderRoute: typeof ScoutProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/explore': {
      id: '/scout/explore'
      path: '/scout/explore'
      fullPath: '/scout/explore'
      preLoaderRoute: typeof ScoutExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$userId': {
      id: '/resume/$userId'
      path: '/resume/$userId'
      fullPath: '/resume/$userId'
      preLoaderRoute: typeof ResumeUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/upload': {
      id: '/player/upload'
      path: '/player/upload'
      fullPath: '/player/upload'
      preLoaderRoute: typeof PlayerUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/profile': {
      id: '/player/profile'
      path: '/player/profile'
      fullPath: '/player/profile'
      preLoaderRoute: typeof PlayerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/explore': {
      id: '/player/explore'
      path: '/player/explore'
      fullPath: '/player/explore'
      preLoaderRoute: typeof PlayerExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  MissionRoute: MissionRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafeScoutingRoute: SafeScoutingRoute,
  ApiHealthRoute: ApiHealthRoute,
  PlayerExploreRoute: PlayerExploreRoute,
  PlayerProfileRoute: PlayerProfileRoute,
  PlayerUploadRoute: PlayerUploadRoute,
  ResumeUserIdRoute: ResumeUserIdRoute,
  ScoutExploreRoute: ScoutExploreRoute,
  ScoutProfileRoute: ScoutProfileRoute,
  ScoutSelectionsRoute: ScoutSelectionsRoute,
  PlayerIndexRoute: PlayerIndexRoute,
  ScoutIndexRoute: ScoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
